services:
  egdc-frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://host.docker.internal:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
